branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- choco install codecov
build_script:
- dotnet build Csi.Plugins.AzureDisk.sln
test_script:
- dotnet test test\Csi.Plugins.AzureDisk.Tests
- OpenCover.Console.exe -hideskipped:Filter -oldstyle -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test test\Csi.Plugins.AzureDisk.Tests" -filter:"+[Csi.Plugins.AzureDisk]*" -output:".\coverage.xml"
- codecov -f "coverage.xml
